"""
Wraps the local dataset (data/searchable_dataset.json) into docs/data.json,
the file the static site's client-side search actually loads.

SUPERSEDED as of the 2026-09-14 rebuild: docs/data.json is now generated by
build_site_data_from_airtable.py, sourced from Donald's live-edited Airtable
bases (data/airtable_live_snapshot.json), which reflect his ongoing manual
review and are the current source of truth. This script is kept for
reference / as a fallback if Airtable access is ever unavailable, but running
it would overwrite docs/data.json with the older, less-curated local dataset.
"""
import json
from datetime import datetime, timezone
from pathlib import Path

ROOT = Path(__file__).parent
DATA = ROOT / "data"
DOCS = ROOT / "docs"


def main():
    with open(DATA / "searchable_dataset.json", encoding="utf-8") as f:
        items = json.load(f)

    payload = {
        "generated_at": datetime.now(timezone.utc).isoformat(),
        "count": len(items),
        "items": items,
    }

    out_path = DOCS / "data.json"
    with open(out_path, "w", encoding="utf-8") as f:
        json.dump(payload, f, ensure_ascii=False, separators=(",", ":"))

    size_kb = out_path.stat().st_size / 1024
    print(f"wrote {out_path}: {len(items)} items, {size_kb:.0f} KB")


if __name__ == "__main__":
    main()
